//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_App
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebAplicationRegisterEmployeeEntities1 : DbContext
    {
        public WebAplicationRegisterEmployeeEntities1()
            : base("name=WebAplicationRegisterEmployeeEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblEmployees> tblEmployees { get; set; }
        public virtual DbSet<tblInicioSesion> tblInicioSesion { get; set; }
        public virtual DbSet<tblRegistro> tblRegistro { get; set; }
    }
}
