//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_App
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblRegistro
    {
        public int IdUser { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        [Required(ErrorMessage = "El campo Email es obligatorio")]
        [EmailAddress(ErrorMessage = "El campo Email no es una dirección de correo electrónico válida.")]
        public string Mail { get; set; }
        public string Phone { get; set; }
        [StringLength(10, MinimumLength = 3, ErrorMessage = "El usuario tiene que tener entre 3 a 10 caracteres")]

        public string Name_User { get; set; }
        [Required(ErrorMessage = "El campo contraseña es obligatorio")]
        public string Password_User { get; set; }
    }
}
